name: tech_tonic
description: Tech + Tonic.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_native_splash: ^2.2.19
  curved_navigation_bar: ^1.0.3
  http: ^0.13.4
  carousel_slider: ^4.0.0
  flutter_quill: ^7.1.4
  flutter_card_swiper: ^4.1.2
  shared_preferences: ^2.1.0
  flutter_rating_bar: ^4.0.1


flutter_native_splash:
  color: '#ffffff'
  image: assets/welcome.png
  android_12:
    color: '#ffffff'
    image: assets/welcome.png
    icon_background: '#ffffff'

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
